### ISSUE TITLE
Fix User edit page bug in development

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/OpenFn-Site#102]
```
2015-03-02T15:09:49.422390+00:00 heroku[router]: at=info method=GET path="/" host=staging-openfn.herokuapp.com request_id=1ae2c146-295e-4dfa-8de3-aa33e392fc4a fwd="66.249.93.230" dyno=web.1 connect=5ms service=37ms status=301 bytes=160
2015-03-02T15:09:48.676074+00:00 heroku[web.1]: State changed from starting to up
2015-03-02T15:09:49.718253+00:00 app[web.1]: ** [NewRelic][03/02/15 17:09:49 +0200 web.1 (20)] INFO : Reporting to: https://rpm.newrelic.com/accounts/819012/applications/5367572
2015-03-02T15:14:16.464469+00:00 heroku[router]: at=info method=GET path="/" host=staging-openfn.herokuapp.com request_id=b3f29235-abf9-4b34-9953-dbe37cec9ee6 fwd="66.249.93.226" dyno=web.1 connect=0ms service=3ms status=301 bytes=160
2015-03-02T15:14:16.862622+00:00 app[web.1]: Started GET "/" for 66.249.93.196 at 2015-03-02 17:14:16 +0200
2015-03-02T15:14:17.014643+00:00 app[web.1]:   Rendered shared/_header.html.erb (2.9ms)
2015-03-02T15:14:16.855863+00:00 app[web.1]: ** [NewRelic][03/02/15 17:14:16 +0200 web.1 (11)] WARN : Ignoring addition of memory because it is already registered.
2015-03-02T15:14:17.015395+00:00 app[web.1]: Completed 200 OK in 36ms (Views: 34.7ms | ActiveRecord: 0.0ms)
2015-03-02T15:14:16.855711+00:00 app[web.1]: ** [NewRelic][03/02/15 17:14:16 +0200 web.1 (11)] WARN : Ignoring addition of cpu because it is already registered.
2015-03-02T15:14:16.856274+00:00 app[web.1]: ** [NewRelic][03/02/15 17:14:16 +0200 web.1 (11)] WARN : Ignoring addition of vm because it is already registered.
2015-03-02T15:14:16.979085+00:00 app[web.1]: Processing by HomeController#index as HTML
2015-03-02T15:14:17.014805+00:00 app[web.1]:   Rendered home/index.html.erb (31.2ms)
2015-03-02T15:14:17.028433+00:00 heroku[router]: at=info method=GET path="/" host=staging-openfn.herokuapp.com request_id=ddb0368f-3a3e-48e9-8bcb-473446fc05be fwd="66.249.93.196" dyno=web.1 connect=0ms service=182ms status=200 bytes=7533
2015-03-02T15:14:17.214527+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=staging-openfn.herokuapp.com request_id=718ce76e-b617-4907-84c8-38a133960ac3 fwd="66.249.93.223" dyno=web.1 connect=0ms service=2ms status=301 bytes=171
2015-03-02T15:14:17.191099+00:00 app[web.1]: ** [NewRelic][03/02/15 17:14:17 +0200 web.1 (11)] INFO : Reporting to: https://rpm.newrelic.com/accounts/819012/applications/5367572
2015-03-02T15:14:17.320398+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=staging-openfn.herokuapp.com request_id=9263409c-657d-43c2-998c-109fdc0628a6 fwd="66.249.93.196" dyno=web.1 connect=1ms service=3ms status=200 bytes=228
2015-03-02T15:14:17.958089+00:00 app[web.1]: Started GET "/" for 197.155.4.24 at 2015-03-02 17:14:17 +0200
2015-03-02T15:14:18.009876+00:00 app[web.1]:   Rendered shared/_invite_modal.html.erb (1.5ms)
2015-03-02T15:14:18.011073+00:00 app[web.1]:   Rendered shared/_header.html.erb (48.1ms)
2015-03-02T15:14:18.011195+00:00 app[web.1]:   Rendered home/index.html.erb (49.9ms)
2015-03-02T15:14:18.011439+00:00 app[web.1]: Completed 200 OK in 51ms (Views: 32.5ms | ActiveRecord: 17.9ms)
2015-03-02T15:14:18.018020+00:00 heroku[router]: at=info method=GET path="/" host=staging-openfn.herokuapp.com request_id=cf3c90d7-94fc-4b2c-9586-aec831394c0f fwd="197.155.4.24" dyno=web.1 connect=0ms service=58ms status=200 bytes=9854
2015-03-02T15:14:18.010922+00:00 app[web.1]:   Rendered shared/_confirm_modal.html.erb (0.4ms)
2015-03-02T15:14:17.960588+00:00 app[web.1]: Processing by HomeController#index as HTML
2015-03-02T15:14:19.726528+00:00 heroku[router]: at=info method=GET path="/the_bridge_templates/static/welcome.html" host=staging-openfn.herokuapp.com request_id=00c3b435-224e-4b3e-9f20-54ca619d956f fwd="197.155.4.24" dyno=web.1 connect=0ms service=2ms status=200 bytes=6890
2015-03-02T15:14:20.027869+00:00 app[web.1]: Started GET "/welcome_stats" for 197.155.4.24 at 2015-03-02 17:14:20 +0200
2015-03-02T15:14:20.106108+00:00 app[web.1]: Completed 200 OK in 73ms (Views: 2.0ms | ActiveRecord: 59.8ms)
2015-03-02T15:14:20.032799+00:00 app[web.1]: Processing by WelcomeStatsController#show as JSON
2015-03-02T15:14:20.115499+00:00 heroku[router]: at=info method=GET path="/welcome_stats" host=staging-openfn.herokuapp.com request_id=4c7c7668-c608-4eef-b867-5b03818b4e2a fwd="197.155.4.24" dyno=web.1 connect=7ms service=85ms status=304 bytes=336
2015-03-02T15:14:24.237654+00:00 app[web.1]: Started GET "/users/4/edit" for 197.155.4.24 at 2015-03-02 17:14:24 +0200
2015-03-02T15:14:24.257200+00:00 app[web.1]: I, [2015-03-02T17:14:24.257123 #11]  INFO -- : get https://gardensforhealth2012.appspot.com/xformsList
2015-03-02T15:14:24.242232+00:00 app[web.1]:   Parameters: {"id"=>"4"}
2015-03-02T15:14:24.242208+00:00 app[web.1]: Processing by UsersController#edit as HTML
2015-03-02T15:14:24.257251+00:00 app[web.1]: user_agent: "OdkAggregate Gem 1.0"
2015-03-02T15:14:24.257249+00:00 app[web.1]: Accept-Language: "en"
2015-03-02T15:14:24.257247+00:00 app[web.1]: D, [2015-03-02T17:14:24.257207 #11] DEBUG -- request: X-OpenRosa-Version: "1.0"
2015-03-02T15:14:24.257252+00:00 app[web.1]: User-Agent: "Faraday v0.8.9"
2015-03-02T15:14:24.466113+00:00 app[web.1]: WWW-Authenticate: "Digest realm=\"VeraSolutions ODK Aggregate\", qop=\"auth\", nonce=\"MTQyNTMxMTA2NDQxNTo4ZDBjZWU0OTFmNGVjNWMyZDFmMDI1Y2ZlMmQ2YzkwZA==\""
2015-03-02T15:14:24.466119+00:00 app[web.1]: Server: "Google Frontend"
2015-03-02T15:14:24.466110+00:00 app[web.1]: D, [2015-03-02T17:14:24.466058 #11] DEBUG -- response: Set-Cookie: "JSESSIONID=gn5YsfutUg71WojBzFZt1Q;Path=/"
2015-03-02T15:14:24.466056+00:00 app[web.1]: I, [2015-03-02T17:14:24.465929 #11]  INFO -- Status: 401
2015-03-02T15:14:24.466821+00:00 app[web.1]: Authorization: "Digest username=\"bridge\", realm=\"VeraSolutions ODK Aggregate\", algorithm=MD5, qop=auth, uri=\"/xformsList\", nonce=\"MTQyNTMxMTA2NDQxNTo4ZDBjZWU0OTFmNGVjNWMyZDFmMDI1Y2ZlMmQ2YzkwZA==\", nc=00000000, cnonce=\"5dec9d61296bf7502d235b1966d154af\", response=\"3fe39f77b432a71ebc574ce3154fc87f\""
2015-03-02T15:14:24.466117+00:00 app[web.1]: Date: "Mon, 02 Mar 2015 15:14:24 GMT"
2015-03-02T15:14:24.466115+00:00 app[web.1]: Content-Type: "text/html; charset=utf-8"
2015-03-02T15:14:24.466818+00:00 app[web.1]: User-Agent: "Faraday v0.8.9"
2015-03-02T15:14:24.466122+00:00 app[web.1]: Alternate-Protocol: "443:quic,p=0.08"
2015-03-02T15:14:24.466120+00:00 app[web.1]: Content-Length: "286"
2015-03-02T15:14:24.466755+00:00 app[web.1]: I, [2015-03-02T17:14:24.466702 #11]  INFO -- : get https://bridge:data2012@gardensforhealth2012.appspot.com/xformsList
2015-03-02T15:14:24.466817+00:00 app[web.1]: user_agent: "OdkAggregate Gem 1.0"
2015-03-02T15:14:24.466813+00:00 app[web.1]: D, [2015-03-02T17:14:24.466775 #11] DEBUG -- request: X-OpenRosa-Version: "1.0"
2015-03-02T15:14:24.466815+00:00 app[web.1]: Accept-Language: "en"
2015-03-02T15:14:24.683404+00:00 app[web.1]: X-OpenRosa-Version: "1.0"
2015-03-02T15:14:24.683381+00:00 app[web.1]: D, [2015-03-02T17:14:24.683335 #11] DEBUG -- response: Expires: "Thu, 01 Jan 1970 00:00:00 GMT"
2015-03-02T15:14:24.683402+00:00 app[web.1]: Set-Cookie: "JSESSIONID=TGgesY4vRFDwIX3Q-wuAKg;Path=/"
2015-03-02T15:14:24.683317+00:00 app[web.1]: I, [2015-03-02T17:14:24.683207 #11]  INFO -- Status: 200
2015-03-02T15:14:24.683410+00:00 app[web.1]: Server: "Google Frontend"
2015-03-02T15:14:24.683413+00:00 app[web.1]: Alternate-Protocol: "443:quic,p=0.08"
2015-03-02T15:14:24.683415+00:00 app[web.1]: Cache-Control: "private"
2015-03-02T15:14:24.683408+00:00 app[web.1]: Content-Type: "text/xml; charset=utf-8"
2015-03-02T15:14:24.683409+00:00 app[web.1]: Date: "Mon, 02 Mar 2015 15:14:24 GMT"
2015-03-02T15:14:24.683412+00:00 app[web.1]: Content-Length: "4365"
2015-03-02T15:14:24.683406+00:00 app[web.1]: X-OpenRosa-Accept-Content-Length: "10485760"
2015-03-02T15:14:28.252133+00:00 heroku[router]: at=info method=GET path="/users/4/edit" host=staging-openfn.herokuapp.com request_id=ebcf0325-348c-44db-8c63-6670aaf08bb5 fwd="197.155.4.24" dyno=web.1 connect=0ms service=4013ms status=500 bytes=1503
2015-03-02T15:14:28.239779+00:00 app[web.1]: Completed 500 Internal Server Error in 3997ms
2015-03-02T15:14:28.246360+00:00 app[web.1]:   app/controllers/users_controller.rb:130:in `set_user_credentials_and_flash'
2015-03-02T15:14:28.246357+00:00 app[web.1]:   app/models/salesforce/listing.rb:4:in `sync!'
2015-03-02T15:14:28.246336+00:00 app[web.1]: 
2015-03-02T15:14:28.246363+00:00 app[web.1]: 
2015-03-02T15:14:28.246340+00:00 app[web.1]: Faraday::Error::ResourceNotFound (NOT_FOUND: The requested resource does not exist):
2015-03-02T15:14:28.246362+00:00 app[web.1]:   app/controllers/users_controller.rb:68:in `edit'
2015-03-02T15:14:28.246358+00:00 app[web.1]:   app/observers/user_observer.rb:10:in `after_save'
2015-03-02T15:14:28.246364+00:00 app[web.1]: 
2015-03-02T15:14:30.209148+00:00 app[web.1]: Started GET "/welcome_stats" for 197.155.4.24 at 2015-03-02 17:14:30 +0200
2015-03-02T15:14:30.391930+00:00 app[web.1]: Completed 200 OK in 68ms (Views: 2.2ms | ActiveRecord: 42.2ms)
2015-03-02T15:14:30.398727+00:00 heroku[router]: at=info method=GET path="/welcome_stats" host=staging-openfn.herokuapp.com request_id=838561ee-3231-425f-84c6-1f76eb10bcbf fwd="197.155.4.24" dyno=web.1 connect=0ms service=190ms status=304 bytes=336
2015-03-02T15:14:30.323976+00:00 app[web.1]: Processing by WelcomeStatsController#show as JSON
2015-03-02T15:14:53.649247+00:00 app[web.1]: Started GET "/users/4/edit" for 197.155.4.24 at 2015-03-02 17:14:53 +0200
2015-03-02T15:14:53.654355+00:00 app[web.1]: Processing by UsersController#edit as HTML
2015-03-02T15:14:53.654382+00:00 app[web.1]:   Parameters: {"id"=>"4"}
2015-03-02T15:14:53.711798+00:00 app[web.1]: I, [2015-03-02T17:14:53.711701 #20]  INFO -- : get https://gardensforhealth2012.appspot.com/xformsList
2015-03-02T15:14:53.711840+00:00 app[web.1]: D, [2015-03-02T17:14:53.711797 #20] DEBUG -- request: X-OpenRosa-Version: "1.0"
2015-03-02T15:14:53.711843+00:00 app[web.1]: Accept-Language: "en"
2015-03-02T15:14:53.711844+00:00 app[web.1]: user_agent: "OdkAggregate Gem 1.0"
2015-03-02T15:14:53.711846+00:00 app[web.1]: User-Agent: "Faraday v0.8.9"
2015-03-02T15:14:53.912259+00:00 app[web.1]: I, [2015-03-02T17:14:53.912158 #20]  INFO -- Status: 401
2015-03-02T15:14:53.912317+00:00 app[web.1]: D, [2015-03-02T17:14:53.912276 #20] DEBUG -- response: Set-Cookie: "JSESSIONID=Ym-SGx0sso7kjMMgYduPdw;Path=/"
2015-03-02T15:14:53.912320+00:00 app[web.1]: WWW-Authenticate: "Digest realm=\"VeraSolutions ODK Aggregate\", qop=\"auth\", nonce=\"MTQyNTMxMTA5Mzg2MDpmNmFjZjNiMTk1M2I5OTFmMzhlYTQxMDJjODJlMTU4NQ==\""
2015-03-02T15:14:53.912321+00:00 app[web.1]: Content-Type: "text/html; charset=utf-8"
2015-03-02T15:14:53.912323+00:00 app[web.1]: Date: "Mon, 02 Mar 2015 15:14:53 GMT"
2015-03-02T15:14:53.912324+00:00 app[web.1]: Server: "Google Frontend"
2015-03-02T15:14:53.912326+00:00 app[web.1]: Content-Length: "286"
2015-03-02T15:14:53.912328+00:00 app[web.1]: Alternate-Protocol: "443:quic,p=0.08"
2015-03-02T15:14:53.913231+00:00 app[web.1]: I, [2015-03-02T17:14:53.913164 #20]  INFO -- : get https://bridge:data2012@gardensforhealth2012.appspot.com/xformsList
2015-03-02T15:14:53.913314+00:00 app[web.1]: D, [2015-03-02T17:14:53.913262 #20] DEBUG -- request: X-OpenRosa-Version: "1.0"
2015-03-02T15:14:53.913316+00:00 app[web.1]: Accept-Language: "en"
2015-03-02T15:14:53.913317+00:00 app[web.1]: user_agent: "OdkAggregate Gem 1.0"
2015-03-02T15:14:53.913319+00:00 app[web.1]: User-Agent: "Faraday v0.8.9"
2015-03-02T15:14:53.913321+00:00 app[web.1]: Authorization: "Digest username=\"bridge\", realm=\"VeraSolutions ODK Aggregate\", algorithm=MD5, qop=auth, uri=\"/xformsList\", nonce=\"MTQyNTMxMTA5Mzg2MDpmNmFjZjNiMTk1M2I5OTFmMzhlYTQxMDJjODJlMTU4NQ==\", nc=00000000, cnonce=\"1c14e7b9a68cfed38e543e81331e0537\", response=\"939ea4c352cb0c1dfdc0d5f6c944f2fc\""
2015-03-02T15:14:54.121472+00:00 app[web.1]: I, [2015-03-02T17:14:54.121351 #20]  INFO -- Status: 200
2015-03-02T15:14:54.121520+00:00 app[web.1]: D, [2015-03-02T17:14:54.121478 #20] DEBUG -- response: Expires: "Thu, 01 Jan 1970 00:00:00 GMT"
2015-03-02T15:14:54.121522+00:00 app[web.1]: Set-Cookie: "JSESSIONID=_A9zFXwA8jBngVYgN-0ssw;Path=/"
2015-03-02T15:14:54.121524+00:00 app[web.1]: X-OpenRosa-Version: "1.0"
2015-03-02T15:14:54.121526+00:00 app[web.1]: X-OpenRosa-Accept-Content-Length: "10485760"
2015-03-02T15:14:54.121527+00:00 app[web.1]: Content-Type: "text/xml; charset=utf-8"
2015-03-02T15:14:54.121529+00:00 app[web.1]: Date: "Mon, 02 Mar 2015 15:14:54 GMT"
2015-03-02T15:14:54.121530+00:00 app[web.1]: Server: "Google Frontend"
2015-03-02T15:14:54.121532+00:00 app[web.1]: Content-Length: "4365"
2015-03-02T15:14:54.121534+00:00 app[web.1]: Alternate-Protocol: "443:quic,p=0.08"
2015-03-02T15:14:54.121535+00:00 app[web.1]: Cache-Control: "private"
2015-03-02T15:14:55.521430+00:00 app[web.1]: 
2015-03-02T15:14:55.521433+00:00 app[web.1]: Faraday::Error::ResourceNotFound (NOT_FOUND: The requested resource does not exist):
2015-03-02T15:14:55.521435+00:00 app[web.1]:   app/models/salesforce/listing.rb:4:in `sync!'
2015-03-02T15:14:55.521437+00:00 app[web.1]:   app/observers/user_observer.rb:10:in `after_save'
2015-03-02T15:14:55.521439+00:00 app[web.1]:   app/controllers/users_controller.rb:130:in `set_user_credentials_and_flash'
2015-03-02T15:14:55.521440+00:00 app[web.1]:   app/controllers/users_controller.rb:68:in `edit'
2015-03-02T15:14:55.521442+00:00 app[web.1]: 
2015-03-02T15:14:55.521444+00:00 app[web.1]: 
2015-03-02T15:14:55.518567+00:00 app[web.1]: Completed 500 Internal Server Error in 1864ms
2015-03-02T15:14:55.530257+00:00 heroku[router]: at=info method=GET path="/users/4/edit" host=staging-openfn.herokuapp.com request_id=f91d05a9-33d0-40f6-b4b9-e6ed9f3ce100 fwd="197.155.4.24" dyno=web.1 connect=0ms service=1878ms status=500 bytes=1503
```

**Comment by taylordowns2000** [comment]
Relevant files are User.rb, User_listing.rb (the thing that sends data to SF.com), User/_form.html, and UserController

**Comment by taylordowns2000** [comment]
This was due to a bad configuration of the User object on Salesforce. It's been fixed.
