### ISSUE TITLE
undefined method `[]' for nil:NilClass on many submissions for Building Tomorrow

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/OpenFn-Site#121]
```
undefined method `[]' for nil:NilClass
/app/app/workers/odk_sf_legacy/odk_to_salesforce/salesforce_objects/import_object.rb:20:in `populate_lookup_field'
/app/app/workers/odk_sf_legacy/odk_to_salesforce/submission_processor.rb:90:in `block in create_in_salesforce'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:46:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:46:in `each'
/app/app/workers/odk_sf_legacy/odk_to_salesforce/submission_processor.rb:79:in `create_in_salesforce'
/app/app/workers/odk_sf_legacy/odk_to_salesforce/submission_processor.rb:67:in `block (2 levels) in process_submission'
/app/app/workers/odk_sf_legacy/odk_to_salesforce/submission_processor.rb:58:in `each'
/app/app/workers/odk_sf_legacy/odk_to_salesforce/submission_processor.rb:58:in `each_with_index'
/app/app/workers/odk_sf_legacy/odk_to_salesforce/submission_processor.rb:58:in `block in process_submission'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:46:in `each'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/relation/delegation.rb:46:in `each'
/app/app/workers/odk_sf_legacy/odk_to_salesforce/submission_processor.rb:55:in `process_submission'
/app/app/workers/odk_sf_legacy/odk_to_salesforce/submission_processor.rb:20:in `perform'
/app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:75:in `execute_job'
/app/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
```

**Comment by taylordowns2000** [comment]
```
2015-03-03T07:05:46.632936+00:00 heroku[router]: at=info method=GET path="/welcome_stats" host=www.openfn.org request_id=29c6b8c2-612d-409f-9077-ac5a59030b31 fwd="105.237.130.46" dyno=web.1 connect=2ms service=56ms status=304 bytes=336
2015-03-03T07:05:50.766077+00:00 app[web.1]:   Parameters: {"mapping_id"=>"246", "id"=>"21710"}
2015-03-03T07:05:50.805018+00:00 app[web.1]:   Rendered shared/_sidebar.html.erb (0.2ms)
2015-03-03T07:05:50.804637+00:00 app[web.1]:   Rendered shared/_flash.html.erb (0.4ms)
2015-03-03T07:05:50.760021+00:00 app[web.1]: Started GET "/mappings/246/submissions/21710" for 105.237.130.46 at 2015-03-03 09:05:50 +0200
2015-03-03T07:05:50.762880+00:00 app[web.1]: Processing by OdkSfLegacy::SubmissionsController#show as HTML
2015-03-03T07:05:50.805459+00:00 app[web.1]: Completed 200 OK in 39ms (Views: 16.3ms | ActiveRecord: 15.8ms)
2015-03-03T07:05:50.790705+00:00 app[web.1]:   Rendered odk_sf_legacy/submissions/show.html.erb within layouts/application (1.2ms)
2015-03-03T07:05:50.800999+00:00 app[web.1]:   Rendered shared/_header.html.erb (9.2ms)
2015-03-03T07:05:50.822562+00:00 heroku[router]: at=info method=GET path="/mappings/246/submissions/21710" host=www.openfn.org request_id=3e56ac5c-7e8f-47b6-ad59-c1ebfb1cd907 fwd="105.237.130.46" dyno=web.1 connect=3ms service=63ms status=200 bytes=11108
2015-03-03T07:05:59.072816+00:00 app[web.1]: Started POST "/mappings/246/submissions/21710/reprocess" for 105.237.130.46 at 2015-03-03 09:05:59 +0200
2015-03-03T07:05:59.136801+00:00 app[web.1]: Completed 302 Found in 55ms (ActiveRecord: 17.5ms)
2015-03-03T07:05:59.082141+00:00 app[web.1]: Processing by OdkSfLegacy::SubmissionsController#reprocess as HTML
2015-03-03T07:05:59.082151+00:00 app[web.1]:   Parameters: {"authenticity_token"=>"Aw/g+7fNgvY6x1+bjA620L3z3+gmIYAIX43JKabw/Po=", "mapping_id"=>"246", "id"=>"21710"}
2015-03-03T07:05:59.136605+00:00 app[web.1]: Redirected to https://www.openfn.org/mappings/246/submissions/21710
2015-03-03T07:05:59.144834+00:00 heroku[router]: at=info method=POST path="/mappings/246/submissions/21710/reprocess" host=www.openfn.org request_id=aaeb8b87-0148-4986-86b7-d0ca2c9055bf fwd="105.237.130.46" dyno=web.1 connect=2ms service=71ms status=302 bytes=1083
2015-03-03T07:05:59.203320+00:00 app[worker.1]: [SubmissionProcessor] [Submission#21710] [Mapping#246] An error occurred
2015-03-03T07:05:59.143094+00:00 app[worker.1]: 2015-03-03T07:05:59.142Z 3 TID-oulo0ea8o OdkSfLegacy::OdkToSalesforce::SubmissionProcessor JID-ee4c5c1d432cf17c79e01548 INFO: start
2015-03-03T07:05:59.210233+00:00 app[worker.1]: 2015-03-03T07:05:59.210Z 3 TID-oulo0ea8o OdkSfLegacy::OdkToSalesforce::SubmissionProcessor JID-ee4c5c1d432cf17c79e01548 INFO: done: 0.067 sec
2015-03-03T07:05:59.203331+00:00 app[worker.1]: [SubmissionProcessor] [Submission#21710] [Mapping#246] undefined method `[]' for nil:NilClass
2015-03-03T07:05:59.151455+00:00 app[worker.1]: [SubmissionProcessor] [Submission#21710] [Mapping#246] Starting
2015-03-03T07:05:59.508250+00:00 heroku[router]: at=info method=GET path="/mappings/246/submissions/21710" host=www.openfn.org request_id=b5c691cf-23b4-4e0a-b73a-ff6593bac15f fwd="105.237.130.46" dyno=web.1 connect=1ms service=49ms status=200 bytes=11108
2015-03-03T07:05:59.493773+00:00 app[web.1]:   Rendered shared/_header.html.erb (1.0ms)
2015-03-03T07:05:59.461304+00:00 app[web.1]: Started GET "/mappings/246/submissions/21710" for 105.237.130.46 at 2015-03-03 09:05:59 +0200
2015-03-03T07:05:59.494465+00:00 app[web.1]:   Rendered shared/_sidebar.html.erb (0.2ms)
2015-03-03T07:05:59.465727+00:00 app[web.1]: Processing by OdkSfLegacy::SubmissionsController#show as HTML
2015-03-03T07:05:59.465737+00:00 app[web.1]:   Parameters: {"mapping_id"=>"246", "id"=>"21710"}
2015-03-03T07:05:59.491674+00:00 app[web.1]:   Rendered odk_sf_legacy/submissions/show.html.erb within layouts/application (4.7ms)
2015-03-03T07:05:59.494167+00:00 app[web.1]:   Rendered shared/_flash.html.erb (0.2ms)
2015-03-03T07:05:59.495012+00:00 app[web.1]: Completed 200 OK in 29ms (Views: 8.4ms | ActiveRecord: 13.7ms)
```

**Comment by taylordowns2000** [comment]
Think that this is due to BT changing salesforce credentials. We'll need to think about what happens to old mappings when credentials are changed. This is a #legacy problem.
